const countryList = {
    "Belarusian": 'be',
    "Bosnian": 'bs',
    "Bulgarian": 'bg',
    "Croatian": 'hr',
    "Czech": 'cs',
    "Danish": 'da',
    "Dutch": 'nl',
    "English": 'en',
    "Esperanto": 'eo',
    "Estonian": 'et',
    "Filipino": 'tl',
    "Finnish": 'fi',
    "French": 'fr',
    "Frisian": 'fy',
    "Galician": 'gl',
    "Georgian": 'ka',
    "German": 'de',
    "Greek": 'el',
    "Hawaiian": 'haw',
    "Hungarian": 'hu',
    "Icelandic": 'is',
    "Indonesian": 'id',
    "Irish": 'ga',
    "Latin": 'la',
    "Latvian": 'lv',
    "Lithuanian": 'lt',
    "Luxembourgish": 'lb',
    "Macedonian": 'mk',
    "Polish": 'pl',
    "Portuguese": 'pt',
    "Romanian": 'ro',
    "Spanish": 'es',
    "Swedish": 'sv',
    "Ukrainian": 'uk',
};

